# Allow sudo to use aliases
alias sudo='sudo '

## GNU Screen
# Start screen dev environment
alias screendev='screen -c ~/.screen/main.layout'
# Kill all detached sessions
alias screenkill='screen -ls | grep Detached | cut -d. -f1 | awk "{print $1}" | xargs -r kill'
